### PR TITLE
delete selected node

### PR DESCRIPTION
**Pull request by irfanabliz**
when there is node selection, if pressed `Del` on keyboard, will remove that node

### CODE REVIEW

**Comment by StaffEngineer** [comment]
@irfanabliz does it interfer with removing selected text inside node?

**Comment by irfanabliz** [comment]
@StaffEngineer yes it does, it removes the text inside, should keep the text?

**Comment by irfanabliz** [comment]
basically it should be the same behaviour as the `delete element` button for selected node

**Comment by StaffEngineer** [comment]
@irfanabliz when text selected inside node `delete` should remove text rather than node (if it's current behaviour).

**Comment by StaffEngineer** [comment]
Let me test it tomorrow, not on PC atm.

**Comment by irfanabliz** [comment]
> @irfanabliz when text selected inside node `delete` should remove text rather than node (if it's current behaviour).

so current behaviour is when selected text inside of the node (node will also be selected) and `remove element` button will remove the node as well as text inside

**Comment by StaffEngineer** [comment]
Yeah, it's all good... since selected text still can be deleted by backspace key.

**Review by StaffEngineer — APPROVED** [review]

**Pull request merged**
